/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiRomsUploadRouteImport } from './routes/api/roms/upload'
import { Route as ApiRomsServeRouteImport } from './routes/api/roms/serve'
import { Route as ApiRomsProxyRouteImport } from './routes/api/roms/proxy'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRomsUploadRoute = ApiRomsUploadRouteImport.update({
  id: '/api/roms/upload',
  path: '/api/roms/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRomsServeRoute = ApiRomsServeRouteImport.update({
  id: '/api/roms/serve',
  path: '/api/roms/serve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRomsProxyRoute = ApiRomsProxyRouteImport.update({
  id: '/api/roms/proxy',
  path: '/api/roms/proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/play/$slug': typeof PlaySlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/roms/proxy': typeof ApiRomsProxyRoute
  '/api/roms/serve': typeof ApiRomsServeRoute
  '/api/roms/upload': typeof ApiRomsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/play/$slug': typeof PlaySlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/roms/proxy': typeof ApiRomsProxyRoute
  '/api/roms/serve': typeof ApiRomsServeRoute
  '/api/roms/upload': typeof ApiRomsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/play/$slug': typeof PlaySlugRoute
  '/u/$username': typeof UUsernameRoute
  '/api/roms/proxy': typeof ApiRomsProxyRoute
  '/api/roms/serve': typeof ApiRomsServeRoute
  '/api/roms/upload': typeof ApiRomsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/profile'
    | '/api/health'
    | '/play/$slug'
    | '/u/$username'
    | '/api/roms/proxy'
    | '/api/roms/serve'
    | '/api/roms/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/profile'
    | '/api/health'
    | '/play/$slug'
    | '/u/$username'
    | '/api/roms/proxy'
    | '/api/roms/serve'
    | '/api/roms/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/library'
    | '/_authenticated/profile'
    | '/api/health'
    | '/play/$slug'
    | '/u/$username'
    | '/api/roms/proxy'
    | '/api/roms/serve'
    | '/api/roms/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PlaySlugRoute: typeof PlaySlugRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiRomsProxyRoute: typeof ApiRomsProxyRoute
  ApiRomsServeRoute: typeof ApiRomsServeRoute
  ApiRomsUploadRoute: typeof ApiRomsUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/roms/upload': {
      id: '/api/roms/upload'
      path: '/api/roms/upload'
      fullPath: '/api/roms/upload'
      preLoaderRoute: typeof ApiRomsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roms/serve': {
      id: '/api/roms/serve'
      path: '/api/roms/serve'
      fullPath: '/api/roms/serve'
      preLoaderRoute: typeof ApiRomsServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roms/proxy': {
      id: '/api/roms/proxy'
      path: '/api/roms/proxy'
      fullPath: '/api/roms/proxy'
      preLoaderRoute: typeof ApiRomsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  ApiHealthRoute: ApiHealthRoute,
  PlaySlugRoute: PlaySlugRoute,
  UUsernameRoute: UUsernameRoute,
  ApiRomsProxyRoute: ApiRomsProxyRoute,
  ApiRomsServeRoute: ApiRomsServeRoute,
  ApiRomsUploadRoute: ApiRomsUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
